"""Event System routes - Event log, subscriptions, and manual triggers"""
from fastapi import APIRouter, HTTPException, Depends, Query
from typing import List, Optional
from datetime import datetime, timezone

from database import db
from models import User
from services.utils import get_current_user, check_master_admin
from services.event_system import event_bus, EventType

router = APIRouter(prefix="/events", tags=["Event System"])


@router.get("")
async def get_events(
    event_type: Optional[str] = None,
    source_module: Optional[str] = None,
    limit: int = Query(default=100, le=500),
    current_user: User = Depends(get_current_user)
):
    """Get event log with filters"""
    query = {}
    
    if event_type:
        query["event_type"] = event_type
    if source_module:
        query["source_module"] = source_module
    
    events = await db.events.find(
        query, {"_id": 0}
    ).sort("timestamp", -1).to_list(limit)
    
    return events


@router.get("/types")
async def get_event_types():
    """Get all available event types"""
    return {
        "event_types": [
            {"value": e.value, "name": e.name} 
            for e in EventType
        ]
    }


@router.get("/stats")
async def get_event_stats(
    current_user: User = Depends(get_current_user)
):
    """Get event statistics"""
    # Count by event type
    pipeline = [
        {"$group": {
            "_id": "$event_type",
            "count": {"$sum": 1}
        }},
        {"$sort": {"count": -1}}
    ]
    
    type_stats = await db.events.aggregate(pipeline).to_list(100)
    
    # Count by source module
    module_pipeline = [
        {"$group": {
            "_id": "$source_module",
            "count": {"$sum": 1}
        }},
        {"$sort": {"count": -1}}
    ]
    
    module_stats = await db.events.aggregate(module_pipeline).to_list(100)
    
    # Recent events (last 24 hours)
    from datetime import timedelta
    yesterday = datetime.now(timezone.utc) - timedelta(hours=24)
    recent_count = await db.events.count_documents({
        "timestamp": {"$gte": yesterday.isoformat()}
    })
    
    # Total events
    total = await db.events.count_documents({})
    
    return {
        "total_events": total,
        "events_last_24h": recent_count,
        "by_type": [{"event_type": s["_id"], "count": s["count"]} for s in type_stats],
        "by_module": [{"module": s["_id"], "count": s["count"]} for s in module_stats]
    }


@router.get("/recent")
async def get_recent_events(
    limit: int = Query(default=20, le=100),
    current_user: User = Depends(get_current_user)
):
    """Get most recent events"""
    events = await db.events.find(
        {}, {"_id": 0}
    ).sort("timestamp", -1).to_list(limit)
    
    return events


@router.get("/alerts")
async def get_alerts(
    is_read: Optional[bool] = None,
    severity: Optional[str] = None,
    limit: int = Query(default=50, le=200),
    current_user: User = Depends(get_current_user)
):
    """Get system alerts generated by events"""
    query = {}
    
    if is_read is not None:
        query["is_read"] = is_read
    if severity:
        query["severity"] = severity
    
    alerts = await db.alerts.find(
        query, {"_id": 0}
    ).sort("created_at", -1).to_list(limit)
    
    return alerts


@router.put("/alerts/{alert_id}/read")
async def mark_alert_read(
    alert_id: str,
    current_user: User = Depends(get_current_user)
):
    """Mark an alert as read"""
    result = await db.alerts.update_one(
        {"id": alert_id},
        {"$set": {"is_read": True, "read_at": datetime.now(timezone.utc).isoformat()}}
    )
    
    if result.modified_count == 0:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    return {"message": "Alert marked as read"}


@router.put("/alerts/read-all")
async def mark_all_alerts_read(
    current_user: User = Depends(get_current_user)
):
    """Mark all alerts as read"""
    result = await db.alerts.update_many(
        {"is_read": False},
        {"$set": {"is_read": True, "read_at": datetime.now(timezone.utc).isoformat()}}
    )
    
    return {"message": f"Marked {result.modified_count} alerts as read"}


@router.post("/publish")
async def publish_event_manual(
    event_type: str,
    payload: dict,
    source_module: str = "manual",
    current_user: User = Depends(get_current_user)
):
    """Manually publish an event (Master Admin only)"""
    check_master_admin(current_user)
    
    # Validate event type
    try:
        et = EventType(event_type)
    except ValueError:
        raise HTTPException(
            status_code=400, 
            detail=f"Invalid event type: {event_type}. Valid types: {[e.value for e in EventType]}"
        )
    
    # Publish event
    event = await event_bus.publish(et, payload, source_module)
    
    return {
        "message": "Event published",
        "event_id": event.id,
        "handlers_triggered": event.handlers_triggered
    }


@router.get("/subscriptions")
async def get_subscriptions(
    current_user: User = Depends(get_current_user)
):
    """Get current event subscriptions (handler registrations)"""
    subscriptions = {}
    
    for event_type, handlers in event_bus._handlers.items():
        if handlers:
            subscriptions[event_type.value] = [h.__name__ for h in handlers]
    
    return subscriptions
