"""
MRP (Material Requisition Planning) Models

The MRP module plans raw material requirements for the next 12 months:
- Month 1: Uses actual production_plans (SKU-level, day-wise)
- Months 2-12: Uses model_level_forecasts, split proportionally to Bidso SKUs
  using a 6-month rolling ratio based on historical production_plans data

Key Collections:
- model_level_forecasts: Model-level quantity forecasts for future months
- rm_procurement_parameters: RM-specific parameters (MOQ, lead time, safety stock, supplier)
- mrp_runs: Historical MRP calculation runs with recommendations
- mrp_draft_pos: Draft purchase orders generated by MRP
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from enum import Enum
import uuid


# ============ Enums ============

class MRPRunStatus(str, Enum):
    DRAFT = "DRAFT"
    CALCULATED = "CALCULATED"
    APPROVED = "APPROVED"
    PO_GENERATED = "PO_GENERATED"
    CANCELLED = "CANCELLED"


class DraftPOStatus(str, Enum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    SENT = "SENT"
    CANCELLED = "CANCELLED"


# ============ Model Level Forecasts ============

class ModelLevelForecast(BaseModel):
    """
    Model-level forecast for a specific month.
    Used for Months 2-12 in MRP calculation.
    """
    model_config = ConfigDict(extra="ignore")
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    model_id: str  # Reference to models collection
    model_code: str
    model_name: str
    vertical_id: str
    vertical_code: str
    
    # Forecast period
    month_year: str  # Format: "2026-04" (YYYY-MM)
    
    # Forecast quantity at model level
    forecast_qty: int
    
    # Audit
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: Optional[str] = None
    updated_at: Optional[datetime] = None
    updated_by: Optional[str] = None


class ModelLevelForecastCreate(BaseModel):
    """Create model level forecast"""
    model_id: str
    month_year: str  # "YYYY-MM"
    forecast_qty: int


class ModelLevelForecastUpdate(BaseModel):
    """Update model level forecast"""
    forecast_qty: Optional[int] = None


# ============ RM Procurement Parameters ============

class RMProcurementParameters(BaseModel):
    """
    RM-specific procurement parameters used in MRP calculations.
    """
    model_config = ConfigDict(extra="ignore")
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    rm_id: str  # Reference to raw_materials collection
    rm_name: Optional[str] = None
    category: Optional[str] = None
    
    # Inventory parameters
    safety_stock: float = 0  # Minimum stock to maintain
    reorder_point: float = 0  # When to trigger reorder
    
    # Ordering parameters
    moq: float = 1  # Minimum Order Quantity
    batch_size: float = 1  # Order in multiples of this
    lead_time_days: int = 7  # Days from PO to delivery
    
    # Preferred supplier (auto-assigned)
    preferred_vendor_id: Optional[str] = None
    preferred_vendor_name: Optional[str] = None
    
    # Price info (cached from vendor_rm_prices)
    unit_price: Optional[float] = None
    currency: str = "INR"
    
    # Status
    is_active: bool = True
    
    # Audit
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None


class RMProcurementParametersCreate(BaseModel):
    """Create RM procurement parameters"""
    rm_id: str
    safety_stock: float = 0
    reorder_point: float = 0
    moq: float = 1
    batch_size: float = 1
    lead_time_days: int = 7
    preferred_vendor_id: Optional[str] = None


class RMProcurementParametersUpdate(BaseModel):
    """Update RM procurement parameters"""
    safety_stock: Optional[float] = None
    reorder_point: Optional[float] = None
    moq: Optional[float] = None
    batch_size: Optional[float] = None
    lead_time_days: Optional[int] = None
    preferred_vendor_id: Optional[str] = None


# ============ MRP Run ============

class SKURollingRatio(BaseModel):
    """Rolling ratio for a single SKU within a model"""
    bidso_sku_id: str
    bidso_sku_name: str
    historical_qty: int  # Total qty in last 6 months
    ratio: float  # 0.0 to 1.0


class ModelSKUSplit(BaseModel):
    """How a model's forecast is split into SKUs"""
    model_id: str
    model_code: str
    model_name: str
    model_forecast_qty: int
    sku_splits: List[Dict[str, Any]]  # [{bidso_sku_id, ratio, allocated_qty}]


class RMRequirement(BaseModel):
    """Calculated RM requirement from BOM explosion"""
    rm_id: str
    rm_name: str
    category: str
    total_required: float  # From BOM explosion
    current_stock: float  # Current inventory
    safety_stock: float
    net_requirement: float  # total_required + safety_stock - current_stock
    moq: float
    batch_size: float
    order_qty: float  # Rounded up to MOQ/batch
    lead_time_days: int
    required_by_date: str  # When RM is needed
    order_date: str  # When PO should be placed
    vendor_id: Optional[str] = None
    vendor_name: Optional[str] = None
    unit_price: Optional[float] = None
    total_cost: Optional[float] = None
    # Source breakdown - which SKUs need this RM
    sku_breakdown: List[Dict[str, Any]] = []  # [{sku_id, qty_needed}]


class MRPRun(BaseModel):
    """
    An MRP calculation run.
    Stores the complete calculation results for audit and review.
    """
    model_config = ConfigDict(extra="ignore")
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    run_code: str  # Auto-generated: MRP-YYYYMMDD-HHMMSS
    
    # Run parameters
    run_date: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    planning_horizon_months: int = 12
    
    # Status
    status: MRPRunStatus = MRPRunStatus.DRAFT
    
    # Month 1 data (from production_plans)
    month1_data: Dict[str, Any] = {}  # {sku_id: qty}
    
    # Months 2-12 data (from model forecasts + rolling ratio)
    model_splits: List[ModelSKUSplit] = []
    
    # Aggregated SKU requirements (all 12 months)
    sku_requirements: Dict[str, int] = {}  # {bidso_sku_id: total_qty}
    
    # BOM explosion results - RM requirements
    rm_requirements: List[RMRequirement] = []
    
    # Summary stats
    total_skus: int = 0
    total_rms: int = 0
    total_order_value: float = 0
    
    # Audit
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: Optional[str] = None
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None


# ============ MRP Draft PO ============

class DraftPOLine(BaseModel):
    """Line item in a draft PO"""
    rm_id: str
    rm_name: str
    category: str
    quantity: float
    unit_price: float
    line_total: float
    required_by_date: str
    # Source MRP requirement IDs
    mrp_rm_requirements: List[str] = []


class MRPDraftPO(BaseModel):
    """
    Draft Purchase Order generated by MRP.
    Consolidated by vendor.
    """
    model_config = ConfigDict(extra="ignore")
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    draft_po_code: str  # Auto-generated: DPO-YYYYMMDD-XXX
    
    # Source MRP run
    mrp_run_id: str
    mrp_run_code: str
    
    # Vendor info
    vendor_id: str
    vendor_name: str
    
    # Lines
    lines: List[DraftPOLine] = []
    
    # Totals
    total_items: int = 0
    total_amount: float = 0
    currency: str = "INR"
    
    # Dates
    suggested_order_date: str
    expected_delivery_date: str
    
    # Status
    status: DraftPOStatus = DraftPOStatus.DRAFT
    
    # Converted PO reference
    converted_po_id: Optional[str] = None
    converted_po_number: Optional[str] = None
    
    # Audit
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None


# ============ Response Models ============

class MRPRunSummary(BaseModel):
    """Summary view of an MRP run"""
    id: str
    run_code: str
    run_date: datetime
    status: str
    planning_horizon_months: int
    total_skus: int
    total_rms: int
    total_order_value: float
    created_by: Optional[str] = None


class MRPDashboardStats(BaseModel):
    """Dashboard statistics for MRP"""
    total_runs: int
    pending_approval: int
    total_draft_pos: int
    pending_po_approval: int
    last_run_date: Optional[datetime] = None
    total_rm_shortage: int
    total_order_value_pending: float
